apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod
  labels:
    name: gitrepo-volume-pod
spec:
  containers:
 
  - image: nginx:alpine
    name: web-server
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
  - image: sealtv/git-sync
    name: git-sync
    env:
      - name: GIT_SYNC_REPO
        value: https://github.com/SealTV/kubia-website-example.git
      - name: GIT_SYNC_DEST
        value: '/git'
      - name: GIT_SYNC_BRANCH
        value: 'master'
      - name: GIT_SYNC_WAIT
        value: '10'
    volumeMounts:
      - name: html
        mountPath: /git
  dnsConfig:
    searches:
      - github.com
    

  volumes:
    - name: html
      gitRepo:
        repository: https://github.com/SealTV/kubia-website-example.git
        revision: master
        directory: .