apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
      - containerPort: 27017
        protocol: TCP
    volumeMounts:
      - name: mongodb-data
        mountPath: /data/db
  volumes:
    - name: mongodb-data
      persistentVolumeClaim:
        claimName: mongodb-pvc