apiVersion: v1
kind: Pod
metadata:
  name: curl-with-amabassador
  labels:
    name: curl-with-amabassador
spec:
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: ambassador
    image: luksa/kubectl-proxy:1.6.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"