apiVersion: v1
kind: Pod
metadata:
  name: gokubia-liveness
spec:
  containers:
  - name: gokubia
    image: sealtv/gokubia-unhealthy
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15