apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: gokubia
spec:
  serviceName: gokubia
  selector:
    matchLabels:
      app: gokubia
  replicas: 2
  template:
    metadata:
      labels:
        app: gokubia
    spec:
      containers:
      - name: gokubia
        image: sealtv/gokubia-pet-peers:v0.10
        args: ["-df", "/var/data/gokubia.txt", "-domain", "gokubia.default.svc.cluster.local"]
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /var/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        resources:
          requests:
            storage: 1Mi
        accessModes:
          - ReadWriteOnce