apiVersion: v1
kind: Pod
metadata:
  name: curl-custo-sa
  labels:
    name: curl-custo-sa
spec:
  serviceAccountName: foo
  containers:
  - name: main
    image: tutum/curl
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    command: ["sleep", "999999999"]
  - name: ambasador
    image: luksa/kubectl-proxy:1.6.2
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
