apiVersion: v1
kind: Pod
metadata:
  name: fortune-env-from-configmap
spec:
  # automountServiceAccountToken: false
  imagePullSecrets:
    - name: dockerhubsecret
  containers:
  - image: sealtv/fortune:env
    name: fortune-env
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: INTERVAL
        valueFrom:
          configMapKeyRef:
            name: fortune-config
            key: sleep-interval
      - name: FOO_SECRET
        valueFrom:
          secretKeyRef:
            key: foo
            name: fortune-https
    volumeMounts:
      - name: html
        mountPath: /var/htdocs
  # WEB SERVER
  - image: nginx:alpine
    name: web-server
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
      - name: config
        mountPath: /etc/nginx/conf.d
        readOnly: true 
      - name: certs
        mountPath: /etc/nginx/certs/
        readOnly: true     
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        protocol: TCP
  volumes:
    - name: html
      emptyDir: 
        medium: Memory
    - name: config
      configMap:
        name: fortune-config
        items:
          - key: my-ngix-config.conf
            path: gzip.conf
        defaultMode: 0666
    - name: certs
      secret:
        secretName: fortune-https
