apiVersion: v1
kind: Pod
metadata:
  name: fortune-env-from-configmap
spec:
  containers:
  - image: sealtv/fortune:env
    name: fortune-env
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: INTERVAL
        valueFrom:
          configMapKeyRef:
            name: fortune-config
            key: sleep-interval
    volumeMounts:
      - name: html
        mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        protocol: TCP
  volumes:
    - name: html
      emptyDir: 
        medium: Memory
