apiVersion: v1
kind: Pod
metadata:
  name: gokubia-gpu
  labels:
    name: gokubia
    creation_method: manual
    env: prod
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - name: gokubia
    image: sealtv/gokubia
    ports:
      - containerPort: 8080
        protocol: TCP
