apiVersion: v1
kind: Pod
metadata:
  name: gokubia-manual
  labels:
    name: gokubia
spec:
  containers:
  - name: gokubia
    image: sealtv/gokubia
    resources:
      limits:
        memory: "500Mi"
    ports:
      - containerPort: 8080
        protocol: TCP
