apiVersion: v1
kind: Pod
metadata:
  name: gokubia-manual-v2
  labels:
    name: gokubia
    creation_method: manual
    env: prod
spec:
  containers:
  - name: gokubia
    image: sealtv/gokubia
    ports:
      - containerPort: 8080
        protocol: TCP
