# apiVersion: v1
# kind: ReplicationController
# metadata:
#   name: gokubia-v1
# spec:
#   replicas: 3
#   selector:
#     app: gokubia
#   template:
#     metadata:
#       name: gokubia
#       labels:
#         app: gokubia
#     spec:
#       containers:
#         - name: gokubia
#           image: sealtv/gokubia:v1
#           ports:
#             - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gokubia
spec:
  type: LoadBalancer
  selector:
    app: gokubia
  ports:
  - port: 80
    targetPort: 8080
